//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhPython.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhPython.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _checked {
            get {
                object obj = ResourceManager.GetObject("_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _unchecked {
            get {
                object obj = ResourceManager.GetObject("_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This component allows to use both RhinoCommon and RhinoScript from within
        ///Grasshopper. Here some Q&amp;As.&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;b&gt;How can I use RhinoCommon?&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;By importing from the Rhino module, for example by writing:&lt;/p&gt;
        ///&lt;pre style=&quot;font-size: smaller&quot;&gt;from Rhino.Geometry import Point3d, Line&lt;/pre&gt;
        ///&lt;p&gt;...and then assigning some new geometry to the results&lt;/p&gt;
        ///&lt;pre style=&quot;font-size: smaller&quot;&gt;a = Line(Point3d(1, 2, 3), Point3d(10, 11, 12))&lt;/pre&gt;
        ///
        ///&lt;p&gt;&lt;b&gt;How can I use RhinoScript?&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;By importin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpText {
            get {
                return ResourceManager.GetString("helpText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap python {
            get {
                object obj = ResourceManager.GetObject("python", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # sample script to show how to use this component and rhinoscriptsyntax
        ///import math
        ///import rhinoscriptsyntax as rs
        ///
        ///if x is None: x = 24    # if nothing is connected to x, set x to something
        ///
        ///circles = []            # create a list. We will add IDs to it later on
        ///radii = []              # ...and another one
        ///
        ///for i in range(x):
        ///    pt = (i, math.cos(i), 0)             # a tuple (here for a point)
        ///    
        ///    id1 = rs.AddCircle(pt, 0.3)
        ///    circles.append(id1)
        ///    endPt = rs.PointAdd(pt, (0, 0.3, 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sampleScript {
            get {
                return ResourceManager.GetString("sampleScript", resourceCulture);
            }
        }
    }
}
